#!/usr/bin/env bash

run(){
  set -x
  bash -c "$@"
  set +x
}

if [ "$1" == "on" ]; then
  run "sudo systemctl start k3s docker tigervncserver@:1"
elif [ "$1" == "off" ]; then
  run "sudo systemctl stop k3s docker tigervncserver@:1"
else
  echo "Invalid argument. Please use 'on' or 'off'."
  exit 1
fi

