#!/bin/bash

dir="$1/import-location"
maxdepth="$2"
files_organized=0

# if dir does not exist, print error and exit
if [ ! -d "$dir" ]; then
  echo "Error: This is not a standard 'import-location' based directory. Exiting."
  return 1
fi

for file in `find "${dir}" -maxdepth ${maxdepth} -type f`; do
  # Extract creation date from file using exiftool (for images) or stat (for other files)
  if [[ $(echo $file | tr 'A-Z' 'a-z') =~ \.(cr2|dng|jpg|jpeg|png|gif|heic|heif)$ ]]; then
    created_date=$(exiftool -s3 -DateTimeOriginal "$file")
    if [ -z "$created_date" ]; then
      created_date=$(exiftool -s3 -CreateDate "$file")
    fi
  else
    created_date="$(date --date="@$(stat -c "%Y" "$file")" "+%Y:%m:%d")"
  fi
  echo -n "[INFO] $(basename $file): ${created_date}"

  # if year is less than 1970 or empty, skip the file
  if [[ ${created_date:0:4} < 1970 ]] || [ -z "$created_date" ]; then
    echo " [SKIP] invalid date"
    continue
  fi

  # Create directory for the date if it doesn't exist
  dir_name="${created_date:0:4}/${created_date:5:2}/${created_date:8:2}"
  mkdir -p "${dir_name}"
  echo "[MOVE] to ${dir_name}"

  # Move file to its corresponding directory
  mv "$file" "${dir_name}/"
  files_organized=$((files_organized + 1))

done

echo "[LOG] Discovered and organized ${files_organized} files."
