#! /usr/bin/env zsh

mode="$1"
# shift
dirs=("$HOME/.mrsauravsahu/dotfiles" "$HOME/.config/nvim" "$HOME/.config/wezterm")
  
exit_code=0

case "$mode" in
  push)
    echo "Starting git push operation on provided directories..."
    for d in "${dirs[@]}"; do
      if [ -d "$d" ]; then
        echo "Processing '$d'..."
        # Change into the directory and execute git push
        (cd "$d" && git push >/dev/null 2>&1)
        if [ $? -eq 0 ]; then
          echo "[x] $d"
        else
          echo "[ ] $d (push failed)"
        fi
      else
        echo "Directory '$d' does not exist!"
      fi
    done
    ;;
  status)
    echo "Displaying git status for provided directories..."
    for d in "${dirs[@]}"; do
      if [ -d "$d" ]; then
        echo "‣ $d"
        if cd "$d"; then
          count=$(git diff --name-only | wc -l)
          if [ "$count" -gt 0 ]; then
            echo -e "\t 🟡 changes need to be committed: $count file(s)"
            exit_code=1
          else
            echo -e "\t ✅ all changes pushed to remote"
          fi
        fi
      else
        echo "❌ '$d' does not exist!"
      fi
    done
    ;;
  # if [[ "$git_dir" == "$EXPECTED_GIT_DIR" ]]; then
      # echo "Success: detected expected git directory! 🎉"
  # else
      # echo "Fallback: using default git directory 😎"
  # fi
  *)
    echo "Invalid mode: $mode"
    echo "Usage: process_git_dirs <push|status> <dir1> <dir2> …"
    ;;
esac

exit $exit_code

